apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 273444517440.dkr.ecr.us-east-1.amazonaws.com/labs-dvn-repo/dev/backend:v1.0
        ports:
        - containerPort: 80
